### ISSUE TITLE
How to remove the red border.

### ISSUE THREAD

**Issue by sidntrivedi** [KyleAMathews/gatsby-starter-theme-cooper-hewitt#1]
Hey @KyleAMathews , 

I really liked this starter-blog theme since it also incorporates an in-built dark theme. But, I don't know why but I don't have much liking for the red border around it. 

Can you please guide me how to remove it?

Thanks.

**Comment by KyleAMathews** [comment]
It's defined in https://github.com/KyleAMathews/gatsby-theme-cooper-hewitt/blob/master/gatsby-theme-cooper-hewitt/src/gatsby-theme-blog/components/layout.js

You'll want to shadow this component in your site — instructions on shadowing are here: https://www.gatsbyjs.org/blog/2019-04-29-component-shadowing/#reach-skip-nav

Enjoy!

**Comment by sidntrivedi** [comment]
Sure. Thanks a lot 🎉
